#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --no-input
jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/app/notebooks -y --ServerApp.token=''&
python manage.py runserver 0.0.0.0:8000
