#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

HTTP_HOST=${HTTP_HOST-0.0.0.0}
HTTP_PORT=${HTTP_PORT-8000}
DJANGO_ASGI_MODULE=config.asgi
WORKERS=${1:-4}
THREADS=${1:-4}

python /app/manage.py collectstatic --noinput
gunicorn -c compose/production/django/gunicorn.conf.py --workers "$WORKERS" --threads "$THREADS" $DJANGO_ASGI_MODULE:application
